# Proyecto clasificacion de noticias

In [1]:
import pandas as pd
import numpy as np

## Leer DataFrame

In [2]:
df=pd.read_json('datos.json', lines=True)
df

category                                           headline  \
0               CRIME  There Were 2 Mass Shootings In Texas Last Week...   
1       ENTERTAINMENT  Will Smith Joins Diplo And Nicky Jam For The 2...   
2       ENTERTAINMENT    Hugh Grant Marries For The First Time At Age 57   
3       ENTERTAINMENT  Jim Carrey Blasts 'Castrato' Adam Schiff And D...   
4       ENTERTAINMENT  Julianna Margulies Uses Donald Trump Poop Bags...   
...               ...                                                ...   
200848           TECH  RIM CEO Thorsten Heins' 'Significant' Plans Fo...   
200849         SPORTS  Maria Sharapova Stunned By Victoria Azarenka I...   
200850         SPORTS  Giants Over Patriots, Jets Over Colts Among  M...   
200851         SPORTS  Aldon Smith Arrested: 49ers Linebacker Busted ...   
200852         SPORTS  Dwight Howard Rips Teammates After Magic Loss ...   

                 authors                                               link  \
0        Melissa Jeltsen  https://www.huffingtonpost.com/entry/texas-ama...   
1          Andy McDonald  https://www.huffingtonpost.com/entry/will-smit...   
2             Ron Dicker  https://www.huffingtonpost.com/entry/hugh-gran...   
3             Ron Dicker  https://www.huffingtonpost.com/entry/jim-carre...   
4             Ron Dicker  https://www.huffingtonpost.com/entry/julianna-...   
...                  ...                                                ...   
200848  Reuters, Reuters  https://www.huffingtonpost.com/entry/rim-ceo-t...   
200849                    https://www.huffingtonpost.com/entry/maria-sha...   
200850                    https://www.huffingtonpost.com/entry/super-bow...   
200851                    https://www.huffingtonpost.com/entry/aldon-smi...   
200852                    https://www.huffingtonpost.com/entry/dwight-ho...   

                                        short_description       date  
0       She left her husband. He killed their children... 2018-05-26  
1                                Of course it has a song. 2018-05-26  
2       The actor and his longtime girlfriend Anna Ebe... 2018-05-26  
3       The actor gives Dems an ass-kicking for not fi... 2018-05-26  
4       The "Dietland" actress said using the bags is ... 2018-05-26  
...                                                   ...        ...  
200848  Verizon Wireless and AT&T are already promotin... 2012-01-28  
200849  Afterward, Azarenka, more effusive with the pr... 2012-01-28  
200850  Leading up to Super Bowl XLVI, the most talked... 2012-01-28  
200851  CORRECTION: An earlier version of this story i... 2012-01-28  
200852  The five-time all-star center tore into his te... 2012-01-28  

[200853 rows x 6 columns]

In [3]:
df.describe()

C:\Users\szilom_2\AppData\Local\Temp/ipykernel_6568/3627053830.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe()


category        headline authors  \
count     200853          200853  200853   
unique        41          199344   27993   
top     POLITICS  Sunday Roundup           
freq       32739              90   36620   
first        NaN             NaN     NaN   
last         NaN             NaN     NaN   

                                                     link short_description  \
count                                              200853            200853   
unique                                             200812            178353   
top     https://www.huffingtonpost.comhttps://www.wash...                     
freq                                                    2             19712   
first                                                 NaN               NaN   
last                                                  NaN               NaN   

                       date  
count                200853  
unique                 2309  
top     2012-12-21 00:00:00  
freq                    100  
first   2012-01-28 00:00:00  
last    2018-05-26 00:00:00

## Preparar los datos 
- Selección de columnas a usar (categoria, short_description)
- Verificar existencia de valores Nulos
- Verificar existencia de cadenas vacias
- Eliminar en caso de exixtir cadenas vacias
- Balancear Dataset

## - Selección de columnas a usar (categoria, short_description)

In [4]:
df1 = df.iloc[:,[0,4]]
df1

category                                  short_description
0               CRIME  She left her husband. He killed their children...
1       ENTERTAINMENT                           Of course it has a song.
2       ENTERTAINMENT  The actor and his longtime girlfriend Anna Ebe...
3       ENTERTAINMENT  The actor gives Dems an ass-kicking for not fi...
4       ENTERTAINMENT  The "Dietland" actress said using the bags is ...
...               ...                                                ...
200848           TECH  Verizon Wireless and AT&T are already promotin...
200849         SPORTS  Afterward, Azarenka, more effusive with the pr...
200850         SPORTS  Leading up to Super Bowl XLVI, the most talked...
200851         SPORTS  CORRECTION: An earlier version of this story i...
200852         SPORTS  The five-time all-star center tore into his te...

[200853 rows x 2 columns]

## Verificar existencia de valores Nulos

In [5]:
df1.isnull().sum()

category             0
short_description    0
dtype: int64

## Verificar existencia de cadenas vacias

In [6]:
df_cadenavacia=df1['short_description']==''
df_cadenavacia

0         False
1         False
2         False
3         False
4         False
          ...  
200848    False
200849    False
200850    False
200851    False
200852    False
Name: short_description, Length: 200853, dtype: bool

In [7]:
df1[df_cadenavacia]

category short_description
12099           COMEDY                  
12849       WORLD NEWS                  
14119       WORLD NEWS                  
23549            TASTE                  
25814           COMEDY                  
...                ...               ...
198250    QUEER VOICES                  
198265     ENVIRONMENT                  
200129          IMPACT                  
200191    QUEER VOICES                  
200266  STYLE & BEAUTY                  

[19712 rows x 2 columns]

## Eliminar en caso de existir cadenas vacias

In [8]:
df_sinCadenasVacias=df1.drop(df1[df1["short_description"]==""].index)
df_sinCadenasVacias

category                                  short_description
0               CRIME  She left her husband. He killed their children...
1       ENTERTAINMENT                           Of course it has a song.
2       ENTERTAINMENT  The actor and his longtime girlfriend Anna Ebe...
3       ENTERTAINMENT  The actor gives Dems an ass-kicking for not fi...
4       ENTERTAINMENT  The "Dietland" actress said using the bags is ...
...               ...                                                ...
200848           TECH  Verizon Wireless and AT&T are already promotin...
200849         SPORTS  Afterward, Azarenka, more effusive with the pr...
200850         SPORTS  Leading up to Super Bowl XLVI, the most talked...
200851         SPORTS  CORRECTION: An earlier version of this story i...
200852         SPORTS  The five-time all-star center tore into his te...

[181141 rows x 2 columns]

In [9]:
dfp=df_sinCadenasVacias['short_description']==''
df_sinCadenasVacias[dfp]

Empty DataFrame
Columns: [category, short_description]
Index: []

## Balancear Dataset

In [10]:
df_sinCadenasVacias.value_counts('category')

category
POLITICS          29578
WELLNESS          17825
ENTERTAINMENT     13470
STYLE & BEAUTY     9637
TRAVEL             9408
PARENTING          8676
FOOD & DRINK       6217
QUEER VOICES       5570
HEALTHY LIVING     5265
BUSINESS           5077
COMEDY             4417
SPORTS             4221
HOME & LIVING      4192
BLACK VOICES       4122
THE WORLDPOST      3664
WEDDINGS           3651
PARENTS            3556
DIVORCE            3426
WOMEN              3102
IMPACT             3061
CRIME              2675
MEDIA              2275
WEIRD NEWS         2209
WORLD NEWS         2175
TECH               2081
GREEN              2046
TASTE              1940
RELIGION           1858
SCIENCE            1775
MONEY              1706
STYLE              1567
ARTS & CULTURE     1339
ENVIRONMENT        1321
WORLDPOST          1242
FIFTY              1042
GOOD NEWS          1039
LATINO VOICES      1021
CULTURE & ARTS     1019
COLLEGE             921
EDUCATION           892
ARTS                863
dtype: 

In [11]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=0)
df_balanceado, df_balanceado['category']=rus.fit_resample(df_sinCadenasVacias[['short_description']],df_sinCadenasVacias['category'])
df_balanceado

short_description   category
0      One could possibly think that the Dallas-Fort ...       ARTS
1      The conversation between Colm Tóibín and Richa...       ARTS
2      Mozart has yielded some incredible insights ab...       ARTS
3      American artist Jeff Koons (York, Pennsylvania...       ARTS
4      Born in New Zealand and now living in Australi...       ARTS
...                                                  ...        ...
35378  People keep asking me what I think about Europ...  WORLDPOST
35379  The proliferation of Man-Portable Air Defense ...  WORLDPOST
35380  Courtesy of Malaysia Airlines Flight 17, Putin...  WORLDPOST
35381  ROME -- "Welcome, this is a house for all. You...  WORLDPOST
35382  While peace talks are frozen, settlement expan...  WORLDPOST

[35383 rows x 2 columns]

In [12]:
df_balanceado.value_counts('category')

category
ARTS              863
MONEY             863
PARENTS           863
POLITICS          863
QUEER VOICES      863
RELIGION          863
SCIENCE           863
SPORTS            863
STYLE             863
STYLE & BEAUTY    863
TASTE             863
TECH              863
THE WORLDPOST     863
TRAVEL            863
WEDDINGS          863
WEIRD NEWS        863
WELLNESS          863
WOMEN             863
WORLD NEWS        863
PARENTING         863
MEDIA             863
ARTS & CULTURE    863
LATINO VOICES     863
BLACK VOICES      863
BUSINESS          863
COLLEGE           863
COMEDY            863
CRIME             863
CULTURE & ARTS    863
DIVORCE           863
EDUCATION         863
ENTERTAINMENT     863
ENVIRONMENT       863
FIFTY             863
FOOD & DRINK      863
GOOD NEWS         863
GREEN             863
HEALTHY LIVING    863
HOME & LIVING     863
IMPACT            863
WORLDPOST         863
dtype: int64

### Guardar Dataset tratado

In [13]:
df_balanceado.to_json('df_Balanceado_Guardado.json' )

## Train set y Test set

In [14]:
X = df_balanceado.iloc[:,0]
y = df_balanceado.iloc[:,1].values

In [15]:
print(X.head())
print('-----------------------')
print(y)

0    One could possibly think that the Dallas-Fort ...
1    The conversation between Colm Tóibín and Richa...
2    Mozart has yielded some incredible insights ab...
3    American artist Jeff Koons (York, Pennsylvania...
4    Born in New Zealand and now living in Australi...
Name: short_description, dtype: object
-----------------------
['ARTS' 'ARTS' 'ARTS' ... 'WORLDPOST' 'WORLDPOST' 'WORLDPOST']


In [16]:
#Obtener el conjunto de entrenamiento y de prueba
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
print('Numero de registros X_train:',X_train.shape)
print('Numero de registros X_test:',X_test.shape)

Numero de registros X_train: (28306,)
Numero de registros X_test: (7077,)


## TfidfVectorizer (TF-IDF(Frecuencia de Término – Frecuencia Inversa de Documento))
- Obtener las frecuencias de cada palabra, tokenizar, obtener la bolsa de palabras, le da mayor importancia a las palabras que no aparecen en el resto de los registros, se eliminan los stops words

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
X_train_numeros=tfidf.fit_transform(X_train)
X_test_numeros = tfidf.transform(X_test)

In [19]:
tfidf.vocabulary_

{'week': 33572,
 'brought': 4469,
 'big': 3493,
 'headlines': 14197,
 'extreme': 11167,
 'weather': 33541,
 'news': 20962,
 'forest': 12189,
 'service': 27611,
 'said': 26779,
 'massive': 19087,
 'yosemite': 34339,
 'rim': 26235,
 'understand': 32248,
 'hardly': 14027,
 'better': 3422,
 'watch': 33468,
 'cbs': 5345,
 'anchor': 1657,
 'bob': 3871,
 'schieffer': 27144,
 'country': 7324,
 'club': 6180,
 'invocation': 16156,
 'israeli': 16286,
 'prime': 24033,
 'minister': 19828,
 'golda': 13224,
 'meir': 19405,
 'suggest': 29940,
 'palestinians': 22261,
 'forcing': 12154,
 'israel': 16285,
 'kill': 17077,
 'children': 5761,
 'quick': 24679,
 'easy': 9896,
 'riff': 26203,
 'spinach': 29041,
 'ricotta': 26181,
 'cannelloni': 4978,
 'great': 13468,
 'way': 33505,
 'sneak': 28567,
 'greens': 13497,
 'despite': 8614,
 '38': 378,
 'weeks': 33579,
 'megan': 19394,
 'hershfield': 14419,
 'going': 13220,
 'stay': 29385,
 'home': 14659,
 'accord': 811,
 'shows': 28003,
 'humans': 14980,
 'transcend

In [20]:
tfidf.idf_

array([ 8.76595775,  5.81278509, 10.55771722, ..., 10.55771722,
       10.55771722, 10.55771722])

In [21]:
tfidf.get_feature_names()

c:\users\szilom_2\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['00',
 '000',
 '0000',
 '002',
 '00pm',
 '00s',
 '01',
 '010',
 '015',
 '02',
 '0235723',
 '03',
 '04',
 '040',
 '048',
 '05',
 '06',
 '067',
 '07',
 '08',
 '09',
 '098',
 '10',
 '100',
 '1000',
 '100b',
 '100k',
 '100th',
 '101',
 '1017',
 '102',
 '1021',
 '103',
 '1038',
 '10460',
 '105',
 '1050',
 '107th',
 '108',
 '109th',
 '10am',
 '10gen',
 '10k',
 '10s',
 '10th',
 '11',
 '110',
 '112',
 '113',
 '115',
 '116',
 '117',
 '118',
 '1181',
 '11th',
 '12',
 '120',
 '1200',
 '123',
 '123s',
 '124',
 '125',
 '129',
 '12pm',
 '12th',
 '13',
 '130',
 '1313',
 '132',
 '136',
 '137',
 '13th',
 '14',
 '140',
 '142',
 '143',
 '144',
 '145',
 '146th',
 '147',
 '1475',
 '148',
 '1492',
 '14days',
 '14th',
 '15',
 '150',
 '1500',
 '150th',
 '152',
 '153',
 '1546',
 '155',
 '156',
 '157',
 '158',
 '1599',
 '15th',
 '16',
 '160',
 '1612',
 '1615',
 '162',
 '1621',
 '1654',
 '167',
 '16th',
 '17',
 '170',
 '1700s',
 '1708',
 '171',
 '172',
 '1734',
 '175',
 '1750',
 '1782',
 '1793',
 '17th',
 '18',

In [22]:
print(X_train_numeros.shape)

(28306, 34540)


In [23]:
pd.DataFrame.sparse.from_spmatrix(X_train_numeros,index=X_train.index,columns=tfidf.get_feature_names())

00  000  0000  002  00pm  00s   01  010  015   02  ...  животные   за  \
9982   0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...       0.0  0.0   
34910  0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...       0.0  0.0   
14214  0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...       0.0  0.0   
20248  0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...       0.0  0.0   
13244  0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...       0.0  0.0   
...    ...  ...   ...  ...   ...  ...  ...  ...  ...  ...  ...       ...  ...   
20757  0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...       0.0  0.0   
32103  0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...       0.0  0.0   
30403  0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...       0.0  0.0   
21243  0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...       0.0  0.0   
2732   0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...       0.0  0.0   

       зоопарка   из   на  новость  отсутствия  плохая  финансирования  \
9982        0.0  0.0  0.0      0.0         0.0     0.0             0.0   
34910       0.0  0.0  0.0      0.0         0.0     0.0             0.0   
14214       0.0  0.0  0.0      0.0         0.0     0.0             0.0   
20248       0.0  0.0  0.0      0.0         0.0     0.0             0.0   
13244       0.0  0.0  0.0      0.0         0.0     0.0             0.0   
...         ...  ...  ...      ...         ...     ...             ...   
20757       0.0  0.0  0.0      0.0         0.0     0.0             0.0   
32103       0.0  0.0  0.0      0.0         0.0     0.0             0.0   
30403       0.0  0.0  0.0      0.0         0.0     0.0             0.0   
21243       0.0  0.0  0.0      0.0         0.0     0.0             0.0   
2732        0.0  0.0  0.0      0.0         0.0     0.0             0.0   

       харьковского  
9982            0.0  
34910           0.0  
14214           0.0  
20248           0.0  
13244           0.0  
...             ...  
20757           0.0  
32103           0.0  
30403           0.0  
21243           0.0  
2732            0.0  

[28306 rows x 34540 columns]

## Modelo a usar SVM

In [24]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train_numeros, y_train)

SVC()

In [25]:
print(svc.predict(tfidf.transform(['In one text message, Jacqueline Ades allegedly told her date she d like to bathe in his blood.'])))
print(svc.predict(tfidf.transform(['A nasty primary race has made the congressional candidate tell the difficult story of escaping her violent ex-husband'])))
print(svc.predict(tfidf.transform(['The five-time all-star center tore into his teammates Friday night after Orlando committed 23 turnovers en route to losing'])))
print(svc.predict(tfidf.transform(['Maria married the best singer in the United States'])))
print(svc.predict(tfidf.transform(['american football game in mexico'])))
print(svc.predict(tfidf.transform(['E-cigarettes are also dangerous. The WHO revealed that the smoke produced by these devices is as unhealthy as the one that comes from common cigarettes'])))

['CRIME']
['DIVORCE']
['ENTERTAINMENT']
['LATINO VOICES']
['SPORTS']
['HEALTHY LIVING']


In [26]:
#Realizando predicciones
y_predsvc=svc.predict(X_test_numeros[0:1000])

In [27]:
#sklearn tiene una funcion para generar la matriz de confusion en sklearn.mestrics
from sklearn.metrics import confusion_matrix
cmsvc=confusion_matrix(y_test[0:1000],y_predsvc)
print(cmsvc)

[[18  0  0 ...  0  0  0]
 [ 2  4  0 ...  0  0  0]
 [ 1  0  6 ...  1  0  0]
 ...
 [ 0  0  0 ...  5  0  0]
 [ 0  0  0 ...  0  6  3]
 [ 0  2  0 ...  2  3 12]]


In [28]:
from sklearn.metrics import f1_score
f1scoresvc = f1_score(y_test[0:1000],y_predsvc, average = 'macro')
print("F1-score: ",f1scoresvc)

F1-score:  0.33433427447905395


In [29]:
from sklearn.metrics import precision_score
precisionsvc = precision_score(y_test[0:1000],y_predsvc, average ='macro')
print("Precision: ",precisionsvc)

Precision:  0.3678590257081796


In [30]:
from sklearn.metrics import accuracy_score
print("Accuracy_score:", accuracy_score(y_test[0:1000],y_predsvc))

Accuracy_score: 0.328


In [31]:
# ver cual es el score antes de guardar el modelo para despues ver si cuando se cargue de nuevo sigue siendo el mismo.
svc.score(X_test_numeros, y_test)

0.3117140031086619

## Guardar modelo entrenado.

In [32]:
import joblib
joblib.dump(svc, 'modelo_entrenado_svc.pkl') # Guardo el modelo.

['modelo_entrenado_svc.pkl']